# coding: utf-8

# flake8: noqa
"""
    AutoMATES Common Abstract Syntax Tree (CAST) v1

    This document outlines the structure of the CAST that will be used as a generic representation of the semantics of a program written in any language. This will be used when creating functions networks from programs using the University of Arizonas program analysis pipeline.    Generating Python Class Structure   TODO look into https://pypi.org/project/swagger-to/    Generating POJOs TODO look into https://stackoverflow.com/questions/33354557/how-to-generate-java-client-code-for-swagger-rest-api-documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from bin2ast.gcc2cast.cast_model.assignment import Assignment
from bin2ast.gcc2cast.cast_model.ast_node import AstNode
from bin2ast.gcc2cast.cast_model.attribute import Attribute
from bin2ast.gcc2cast.cast_model.binary_op import BinaryOp
from bin2ast.gcc2cast.cast_model.binary_operator import (
    BinaryOperator,
)
from bin2ast.gcc2cast.cast_model.boolean import Boolean
from bin2ast.gcc2cast.cast_model.call import Call
from bin2ast.gcc2cast.cast_model.class_def import ClassDef
from bin2ast.gcc2cast.cast_model.dict import Dict
from bin2ast.gcc2cast.cast_model.expr import Expr
from bin2ast.gcc2cast.cast_model.function_def import FunctionDef
from bin2ast.gcc2cast.cast_model.list import List
from bin2ast.gcc2cast.cast_model.loop import Loop
from bin2ast.gcc2cast.cast_model.model_break import ModelBreak
from bin2ast.gcc2cast.cast_model.model_continue import ModelContinue
from bin2ast.gcc2cast.cast_model.model_if import ModelIf
from bin2ast.gcc2cast.cast_model.model_return import ModelReturn
from bin2ast.gcc2cast.cast_model.module import Module
from bin2ast.gcc2cast.cast_model.name import Name
from bin2ast.gcc2cast.cast_model.number import Number
from bin2ast.gcc2cast.cast_model.set import Set
from bin2ast.gcc2cast.cast_model.source_ref import SourceRef
from bin2ast.gcc2cast.cast_model.string import String
from bin2ast.gcc2cast.cast_model.source_ref import SourceRef
from bin2ast.gcc2cast.cast_model.subscript import Subscript
from bin2ast.gcc2cast.cast_model.tuple import Tuple
from bin2ast.gcc2cast.cast_model.unary_op import UnaryOp
from bin2ast.gcc2cast.cast_model.unary_operator import UnaryOperator
from bin2ast.gcc2cast.cast_model.var import Var
from bin2ast.gcc2cast.cast_model.var_type import VarType
